Update for Zeek plugin reorg.
This is copying over a bunch of cmake/testing infrastructure from the
new spicy-plugin repository. Also adapting to the plugin's new
standalone build, and adding support for installation outside of zkg.

We may eventually factor some of the cmake/testing logic out and have it
shared across the two packages (and potentially other ones as well).

diff --git a/tests/Scripts/run-spicy-config b/tests/Scripts/run-spicy-config
--- a/tests/Scripts/run-spicy-config
+++ b/tests/Scripts/run-spicy-config
@@ -1,15 +1,25 @@
-#! /bin/bash
+#! /bin/sh
 
 base=$(cd $(dirname $0)/.. && pwd)
-spicy_tests=${base}/../../../tests # For in-tree Spicy build
 
+# 1. Explicit override through environment.
 test -n "${SPICY_CONFIG}" && exe="${SPICY_CONFIG}"
 
-if [ -z "${exe}" -a -x ${spicy_tests}/Scripts/build-directory ]; then
-    exe=$(${spicy_tests}/Scripts/build-directory)/bin/spicy-config
+# 2. Take from explicitly specified installation.
+test -z "${exe}" && test -n "${SPICY_INSTALLATION_DIRECTORY}" && exe="${SPICY_INSTALLATION_DIRECTORY}/bin/spicy-config"
+
+# 3. Whatever CMake discovered.
+if [ -z "${exe}" -a -f "$(${base}/Scripts/build-directory)/CMakeCache.txt" ]; then
+    cached=$(cat $(${base}/Scripts/build-directory)/CMakeCache.txt | grep ^SPICY_CONFIG: | cut -d '=' -f 2)
+    test -n "${cached}" && exe=${cached}
 fi
 
+# 4. Take what's in PATH.
 test -z "${exe}" && exe="$(which spicy-config 2>/dev/null)"
-test -z "${exe}" && echo "cannot find spicy-config; make sure it is in PATH or set SPICY_CONFIG" >&2 && exit 1
 
-${exe} $@
+if [ -z "${exe}" -o ! -x "${exe}" ]; then
+    test -n "${SPICY_INSTALLATION_DIRECTORY}" || echo "cannot find spicy-config; make sure it is in PATH or set SPICY_CONFIG" >&2
+    exit 1
+fi
+
+exec ${exe} $@
